package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type sourceRuleSet struct {
	Version int            `json:"version"`
	Rules   []headlessRule `json:"rules"`
}

type headlessRule struct {
	Domain       []string `json:"domain,omitempty"`
	DomainSuffix []string `json:"domain_suffix,omitempty"`
	DomainRegex  []string `json:"domain_regex,omitempty"`
	IPCIDR       []string `json:"ip_cidr,omitempty"`
}

type manifestItem struct {
	ID      string `json:"id"`
	Kind    string `json:"kind"`
	Source  string `json:"source"`
	Entries int    `json:"entries"`
	List    string `json:"list"`
	SingBox string `json:"sing_box"`
}

func main() {
	geoDir := flag.String("geo", "", "666OS geo checkout")
	outDir := flag.String("out", "", "converted output directory")
	flag.Parse()
	if *geoDir == "" || *outDir == "" {
		fatalf("usage: coralbay-ruleconvert -geo DIR -out DIR")
	}
	if err := os.RemoveAll(*outDir); err != nil {
		fatalf("clean output: %v", err)
	}
	var manifest []manifestItem
	for _, kind := range []string{"site", "ip"} {
		files, err := filepath.Glob(filepath.Join(*geoDir, kind, "*.txt"))
		if err != nil {
			fatalf("list %s sources: %v", kind, err)
		}
		sort.Strings(files)
		for _, source := range files {
			item, err := convertFile(*geoDir, *outDir, kind, source)
			if err != nil {
				fatalf("convert %s: %v", source, err)
			}
			manifest = append(manifest, item)
		}
	}
	// The release branch contains a few MRS-only categories with no reversible
	// public source in the geo branch. Publish valid empty artifacts so clients
	// fail closed and the manifest can report zero coverage without broken URLs.
	for _, placeholder := range []struct{ kind, name string }{
		{"site", "advertising"}, {"site", "tracking"}, {"site", "emby"},
		{"ip", "apple"}, {"ip", "emby"},
	} {
		manifest = append(manifest, writePlaceholder(*outDir, placeholder.kind, placeholder.name))
	}
	content, _ := json.MarshalIndent(map[string]any{
		"version": 1, "generator": "CoralBay Rules", "sets": manifest, "count": len(manifest),
	}, "", "  ")
	writeFile(filepath.Join(*outDir, "manifest.json"), append(content, '\n'))
	fmt.Printf("converted %d native rule sets\n", len(manifest))
}

func writePlaceholder(outDir, kind, name string) manifestItem {
	listRelative := filepath.ToSlash(filepath.Join("native", "list", kind, name+".list"))
	jsonRelative := filepath.ToSlash(filepath.Join("native", "sing-box", kind, name+".json"))
	writeFile(filepath.Join(outDir, filepath.FromSlash(listRelative)), []byte("# Empty: 666OS geo has no public reversible source for this MRS-only category\n"))
	content, _ := json.MarshalIndent(sourceRuleSet{Version: 3, Rules: make([]headlessRule, 0)}, "", "  ")
	writeFile(filepath.Join(outDir, filepath.FromSlash(jsonRelative)), append(content, '\n'))
	return manifestItem{ID: kind + "-" + name, Kind: kind, Source: "MRS-only (no reversible geo source)", Entries: 0, List: listRelative, SingBox: jsonRelative}
}

func convertFile(geoDir, outDir, kind, source string) (manifestItem, error) {
	file, err := os.Open(source)
	if err != nil {
		return manifestItem{}, err
	}
	defer file.Close()

	var exact, suffix, regex, cidr, list []string
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 64*1024), 2*1024*1024)
	seen := map[string]bool{}
	for scanner.Scan() {
		value := strings.TrimSpace(scanner.Text())
		if value == "" || strings.HasPrefix(value, "#") || seen[value] {
			continue
		}
		seen[value] = true
		if kind == "ip" {
			cidr = append(cidr, value)
			typeName := "IP-CIDR"
			if strings.Contains(value, ":") {
				typeName = "IP-CIDR6"
			}
			list = append(list, typeName+","+value+",no-resolve")
			continue
		}
		switch {
		case strings.HasPrefix(value, "+."):
			value = strings.TrimPrefix(value, "+.")
			suffix = append(suffix, value)
			list = append(list, "DOMAIN-SUFFIX,"+value)
		case strings.HasPrefix(value, "regex:"):
			value = strings.TrimPrefix(value, "regex:")
			regex = append(regex, value)
			list = append(list, "DOMAIN-REGEX,"+value)
		default:
			exact = append(exact, value)
			list = append(list, "DOMAIN,"+value)
		}
	}
	if err := scanner.Err(); err != nil {
		return manifestItem{}, err
	}
	base := strings.TrimSuffix(filepath.Base(source), filepath.Ext(source))
	id := kind + "-" + base
	listRelative := filepath.ToSlash(filepath.Join("native", "list", kind, base+".list"))
	jsonRelative := filepath.ToSlash(filepath.Join("native", "sing-box", kind, base+".json"))
	listContent := "# Generated by CoralBay Rules from 666OS/rules geo\n" + strings.Join(list, "\n") + "\n"
	writeFile(filepath.Join(outDir, filepath.FromSlash(listRelative)), []byte(listContent))
	rule := headlessRule{Domain: exact, DomainSuffix: suffix, DomainRegex: regex, IPCIDR: cidr}
	jsonContent, _ := json.MarshalIndent(sourceRuleSet{Version: 3, Rules: []headlessRule{rule}}, "", "  ")
	writeFile(filepath.Join(outDir, filepath.FromSlash(jsonRelative)), append(jsonContent, '\n'))
	return manifestItem{ID: id, Kind: kind, Source: strings.TrimPrefix(filepath.ToSlash(source), filepath.ToSlash(geoDir)+"/"), Entries: len(list), List: listRelative, SingBox: jsonRelative}, nil
}

func writeFile(path string, content []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fatalf("create directory: %v", err)
	}
	temp := path + ".next"
	if err := os.WriteFile(temp, content, 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
	if err := os.Rename(temp, path); err != nil {
		fatalf("publish %s: %v", path, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
