[Proxy Group]
国外流量 = select,自动选择,DIRECT,{{ $proxyNames }}
自动选择 = url-test,{{ $proxyNames }}
广告拦截 = select,REJECT,DIRECT
网络测试 = select,国外流量,DIRECT,{{ $proxyNames }}
即时通讯 = select,国外流量,DIRECT,{{ $proxyNames }}
社交平台 = select,国外流量,DIRECT,{{ $proxyNames }}
人工智能 = select,国外流量,DIRECT,{{ $proxyNames }}
开发服务 = select,国外流量,DIRECT,{{ $proxyNames }}
EMBY = select,国外流量,DIRECT,{{ $proxyNames }}
国际媒体 = select,国外流量,DIRECT,{{ $proxyNames }}
游戏平台 = select,国外流量,DIRECT,{{ $proxyNames }}
货币平台 = select,国外流量,DIRECT,{{ $proxyNames }}
谷歌服务 = select,国外流量,DIRECT,{{ $proxyNames }}
脸书服务 = select,国外流量,DIRECT,{{ $proxyNames }}
微软服务 = select,DIRECT,国外流量,{{ $proxyNames }}
苹果服务 = select,DIRECT,国外流量,{{ $proxyNames }}
国内流量 = select,DIRECT,国外流量
漏网之鱼 = select,国外流量,DIRECT,{{ $proxyNames }}

[Rewrite]
^https?:\/\/(www.)?g\.cn 302 https://www.google.com
^https?:\/\/(www.)?google\.cn 302 https://www.google.com

[Remote Rule]
__NATIVE_LIST_BASE_URL__site/private.list, policy = DIRECT, tag = Private, enabled = true
__NATIVE_LIST_BASE_URL__ip/private.list, policy = DIRECT, tag = PrivateIP, enabled = true
__NATIVE_LIST_BASE_URL__site/connectivity-check.list, policy = 网络测试, tag = Speedtest, enabled = true
__NATIVE_LIST_BASE_URL__site/telegram.list, policy = 即时通讯, tag = Telegram, enabled = true
__NATIVE_LIST_BASE_URL__site/category-tm.list, policy = 即时通讯, tag = TM, enabled = true
__NATIVE_LIST_BASE_URL__ip/telegram.list, policy = 即时通讯, tag = TelegramIP, enabled = true
__NATIVE_LIST_BASE_URL__site/category-social-media-!cn.list, policy = 社交平台, tag = SocialMedia, enabled = true
__NATIVE_LIST_BASE_URL__site/category-ai-!cn.list, policy = 人工智能, tag = AI, enabled = true
__NATIVE_LIST_BASE_URL__site/category-dev.list, policy = 开发服务, tag = Dev, enabled = true
__NATIVE_LIST_BASE_URL__site/category-media.list, policy = 国际媒体, tag = Streaming, enabled = true
__NATIVE_LIST_BASE_URL__site/category-games.list, policy = 游戏平台, tag = Games, enabled = true
__NATIVE_LIST_BASE_URL__site/category-cryptocurrency.list, policy = 货币平台, tag = Crypto, enabled = true
__NATIVE_LIST_BASE_URL__site/google.list, policy = 谷歌服务, tag = Google, enabled = true
__NATIVE_LIST_BASE_URL__ip/google.list, policy = 谷歌服务, tag = GoogleIP, enabled = true
__NATIVE_LIST_BASE_URL__site/facebook.list, policy = 脸书服务, tag = Facebook, enabled = true
__NATIVE_LIST_BASE_URL__ip/facebook.list, policy = 脸书服务, tag = FacebookIP, enabled = true
__NATIVE_LIST_BASE_URL__site/microsoft.list, policy = 微软服务, tag = Microsoft, enabled = true
__NATIVE_LIST_BASE_URL__site/apple.list, policy = 苹果服务, tag = Apple, enabled = true
__NATIVE_LIST_BASE_URL__site/cn.list, policy = 国内流量, tag = China, enabled = true
__NATIVE_LIST_BASE_URL__ip/cn.list, policy = 国内流量, tag = ChinaIP, enabled = true
__NATIVE_LIST_BASE_URL__site/geolocation-!cn.list, policy = 国外流量, tag = Proxy, enabled = true

[Rule]
FINAL,漏网之鱼
