[Proxy Group]
{{- if gt (len $supportedProxies) 0 }}
国外流量 = select, 自动选择, DIRECT, {{ template "AllProxyNames" . }}
自动选择 = url-test, {{ template "AllProxyNames" . }}, url=http://www.gstatic.com/generate_204, interval=300
网络测试 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
即时通讯 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
社交平台 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
人工智能 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
开发服务 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
EMBY = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
国际媒体 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
游戏平台 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
货币平台 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
谷歌服务 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
脸书服务 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
微软服务 = select, DIRECT, 国外流量, {{ template "AllProxyNames" . }}
苹果服务 = select, DIRECT, 国外流量, {{ template "AllProxyNames" . }}
漏网之鱼 = select, 国外流量, DIRECT, {{ template "AllProxyNames" . }}
{{- else }}
国外流量 = select, DIRECT
自动选择 = select, DIRECT
网络测试 = select, DIRECT
即时通讯 = select, DIRECT
社交平台 = select, DIRECT
人工智能 = select, DIRECT
开发服务 = select, DIRECT
EMBY = select, DIRECT
国际媒体 = select, DIRECT
游戏平台 = select, DIRECT
货币平台 = select, DIRECT
谷歌服务 = select, DIRECT
脸书服务 = select, DIRECT
微软服务 = select, DIRECT
苹果服务 = select, DIRECT
漏网之鱼 = select, DIRECT
{{- end }}
广告拦截 = select, REJECT, DIRECT
国内流量 = select, DIRECT, 国外流量

[Rule]
RULE-SET,__NATIVE_LIST_BASE_URL__site/private.list,DIRECT
RULE-SET,__NATIVE_LIST_BASE_URL__ip/private.list,DIRECT
RULE-SET,__NATIVE_LIST_BASE_URL__site/connectivity-check.list,网络测试
RULE-SET,__NATIVE_LIST_BASE_URL__site/telegram.list,即时通讯
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-tm.list,即时通讯
RULE-SET,__NATIVE_LIST_BASE_URL__ip/telegram.list,即时通讯
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-social-media-!cn.list,社交平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-ai-!cn.list,人工智能
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-dev.list,开发服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-media.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-games.list,游戏平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-cryptocurrency.list,货币平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/google.list,谷歌服务
RULE-SET,__NATIVE_LIST_BASE_URL__ip/google.list,谷歌服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/facebook.list,脸书服务
RULE-SET,__NATIVE_LIST_BASE_URL__ip/facebook.list,脸书服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/microsoft.list,微软服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/apple.list,苹果服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/cn.list,国内流量
RULE-SET,__NATIVE_LIST_BASE_URL__ip/cn.list,国内流量
RULE-SET,__NATIVE_LIST_BASE_URL__site/geolocation-!cn.list,国外流量
FINAL,漏网之鱼

[Panel]
PanelA = title="订阅信息", content="流量用量: {{ $used }}GB / {{ $total }}GB\n到期时间: {{ $ExpiredAt }}\n更新时间: {{ now | date "2006-01-02 15:04:05" }}", style=info
