[Proxy Group]
国外流量 = select, 自动选择, DIRECT, {{ $proxyNames }}
自动选择 = url-test, {{ $proxyNames }}, url=http://www.gstatic.com/generate_204, interval=300
广告拦截 = select, REJECT, DIRECT
网络测试 = select, 国外流量, DIRECT, {{ $proxyNames }}
即时通讯 = select, 国外流量, DIRECT, {{ $proxyNames }}
社交平台 = select, 国外流量, DIRECT, {{ $proxyNames }}
人工智能 = select, 国外流量, DIRECT, {{ $proxyNames }}
开发服务 = select, 国外流量, DIRECT, {{ $proxyNames }}
EMBY = select, 国外流量, DIRECT, {{ $proxyNames }}
国际媒体 = select, 国外流量, DIRECT, {{ $proxyNames }}
游戏平台 = select, 国外流量, DIRECT, {{ $proxyNames }}
货币平台 = select, 国外流量, DIRECT, {{ $proxyNames }}
谷歌服务 = select, 国外流量, DIRECT, {{ $proxyNames }}
脸书服务 = select, 国外流量, DIRECT, {{ $proxyNames }}
微软服务 = select, DIRECT, 国外流量, {{ $proxyNames }}
苹果服务 = select, DIRECT, 国外流量, {{ $proxyNames }}
国内流量 = select, DIRECT, 国外流量
漏网之鱼 = select, 国外流量, DIRECT, {{ $proxyNames }}

[Rule]
RULE-SET,__NATIVE_LIST_BASE_URL__site/private.list,DIRECT
RULE-SET,__NATIVE_LIST_BASE_URL__ip/private.list,DIRECT,no-resolve
RULE-SET,__NATIVE_LIST_BASE_URL__site/connectivity-check.list,网络测试
RULE-SET,__NATIVE_LIST_BASE_URL__site/telegram.list,即时通讯
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-tm.list,即时通讯
RULE-SET,__NATIVE_LIST_BASE_URL__ip/telegram.list,即时通讯,no-resolve
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-social-media-!cn.list,社交平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/twitter.list,社交平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/instagram.list,社交平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-ai-!cn.list,人工智能
RULE-SET,__NATIVE_LIST_BASE_URL__site/openai.list,人工智能
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-dev.list,开发服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/github.list,开发服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-media.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__site/netflix.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__site/disney.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__site/youtube.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__site/spotify.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__site/tiktok.list,国际媒体
RULE-SET,__NATIVE_LIST_BASE_URL__ip/netflix.list,国际媒体,no-resolve
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-games.list,游戏平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/category-cryptocurrency.list,货币平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/bybit.list,货币平台
RULE-SET,__NATIVE_LIST_BASE_URL__site/google.list,谷歌服务
RULE-SET,__NATIVE_LIST_BASE_URL__ip/google.list,谷歌服务,no-resolve
RULE-SET,__NATIVE_LIST_BASE_URL__site/facebook.list,脸书服务
RULE-SET,__NATIVE_LIST_BASE_URL__ip/facebook.list,脸书服务,no-resolve
RULE-SET,__NATIVE_LIST_BASE_URL__site/microsoft.list,微软服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/onedrive.list,微软服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/apple.list,苹果服务
RULE-SET,__NATIVE_LIST_BASE_URL__site/cn.list,国内流量
RULE-SET,__NATIVE_LIST_BASE_URL__ip/cn.list,国内流量,no-resolve
RULE-SET,__NATIVE_LIST_BASE_URL__site/geolocation-!cn.list,国外流量
FINAL,漏网之鱼,dns-failed

[URL Rewrite]
^https?:\/\/(www.)?g\.cn https://www.google.com 302
^https?:\/\/(www.)?google\.cn https://www.google.com 302
