const $ = id => document.getElementById(id);
async function json(url, opt) { const r = await fetch(url, opt); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || `HTTP ${r.status}`); return d; }
const short = value => value ? value.slice(0, 10) : '—';
const size = bytes => bytes == null ? '—' : bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes/1024).toFixed(1)} KB` : bytes < 1073741824 ? `${(bytes/1048576).toFixed(1)} MB` : `${(bytes/1073741824).toFixed(1)} GB`;
function setState(id, text, ok) { $(id).textContent = text; $(id).className = `value ${ok ? 'ok' : 'bad'}`; }
async function publicStatus() { if (!$('state')) return; try { const d=await json('/api/public/status'),s=d.status||{}; setState('state',d.syncing?'同步中':'正常',true); $('commit').textContent=short(s.commit); $('files').textContent=s.validated_files??'—'; $('synced').textContent=s.synced_at||'—'; } catch { setState('state','异常',false); } }
async function loadRules() { if (!$('ruleRows')) return; const d=await json('/api/public/rules'); $('ruleRows').innerHTML=d.rules.map(r=>`<tr><td><strong>${r.name}</strong><br><small>${r.path}</small></td><td>${r.behavior}<br><small>${r.format}</small></td><td class="${r.cached?'ok':'bad'}">${r.cached?'已缓存':'缺失'}</td><td>${size(r.bytes)}</td><td><a href="${r.original_url}" target="_blank" rel="noreferrer">原链接</a> · <a href="${r.mirror_url}" target="_blank" rel="noreferrer">镜像</a> · <a href="${r.mirror_url}" download>下载</a><details><summary>详情</summary><small>${r.detail}</small></details></td></tr>`).join(''); }
async function loadAdmin() { try { const d=await json('/api/admin/status'),s=d.status||{},c=d.certificate||{},i=d.icons||{}; setState('adminState',d.syncing?'同步中':'正常',!d.last_error); $('adminCommit').textContent=`提交 ${short(s.commit)}`; $('runningVersion').textContent=`v${d.version}`; $('latestVersion').textContent=d.latest_version?`最新 ${d.latest_version}${d.update_available?' · 可升级':' · 已是最新'}`:'暂时无法检查最新版'; setState('certificate',c.ok?`${c.days_remaining} 天`:'异常',c.ok&&c.days_remaining>14); $('certificateIssuer').textContent=c.ok?`${c.issuer} · ${new Date(c.not_after).toLocaleDateString()}`:(c.error||'无法读取'); setState('iconCache',`${i.cached||0} / ${i.expected||27}`,i.ok); $('iconBytes').textContent=size(i.bytes); $('adminFiles').textContent=`${s.validated_files||0} / 33`; $('diskFree').textContent=size(d.disk_free_bytes); $('interval').value=String(d.interval_seconds); $('intervalHint').textContent=`当前每 ${Math.round(d.interval_seconds/3600)} 小时`; $('copyTemplate').dataset.url=d.template_url; $('updateApp').disabled=!d.update_available; $('updateApp').textContent=d.update_available?`升级到 ${d.latest_version}`:'已是最新版本'; const logs=await json('/api/admin/logs'); $('logs').textContent=(logs.logs||[]).join('\n')||'暂无本次运行日志'; const releases=await json('/api/admin/releases'); $('releases').innerHTML=(releases.releases||[]).map(r=>`<div class="release"><code>${short(r.commit)} ${r.active?'（当前）':''}</code>${r.active?'':`<button data-rollback="${r.commit}" class="secondary">回滚</button>`}</div>`).join('')||'暂无历史版本'; document.querySelectorAll('[data-rollback]').forEach(b=>b.onclick=()=>rollback(b.dataset.rollback)); } catch(e) { $('message').textContent=e.message; } }
async function rollback(commit) { if(!confirm(`确认回滚到 ${short(commit)}？`))return; await json('/api/admin/rollback',{method:'POST',headers:{'Content-Type':'application/json','X-CoralBay-Action':'console'},body:JSON.stringify({commit})}); $('message').textContent='回滚完成'; loadAdmin(); }
if ($('sync')) { $('sync').onclick=async()=>{try{await json('/api/admin/sync',{method:'POST',headers:{'X-CoralBay-Action':'console'}});$('message').textContent='同步已启动';setTimeout(loadAdmin,1500)}catch(e){$('message').textContent=e.message}}; $('updateApp').onclick=async()=>{if(!confirm('确认拉取最新镜像并重启 CoralBay Rules？页面可能短暂断开。'))return;await json('/api/admin/update',{method:'POST',headers:{'X-CoralBay-Action':'console'}});$('message').textContent='更新器已启动，请约一分钟后刷新页面'}; $('saveInterval').onclick=async()=>{await json('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json','X-CoralBay-Action':'console'},body:JSON.stringify({interval_seconds:Number($('interval').value)})});$('message').textContent='同步频率已保存';loadAdmin()}; $('copyTemplate').onclick=async()=>{await navigator.clipboard.writeText($('copyTemplate').dataset.url);$('message').textContent='模板链接已复制'}; $('refresh').onclick=()=>{loadAdmin();loadRules()}; $('ruleCard').onclick=()=>$('ruleSection').scrollIntoView({behavior:'smooth'}); loadAdmin(); loadRules(); }
publicStatus();
